services:
  - type: web
    name: seo-boost
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.app:app --timeout 60"
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
